services:
  - type: web
    name: street-vendor-agent
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: IBM_API_KEY
        sync: false
      - key: IBM_PROJECT_ID
        sync: false
      - key: IBM_URL
        sync: false
    autoDeploy: true
